### PR TITLE
[WIP] Refactor docker-osm setup for smaller scale integration tests

### PR DESCRIPTION
**Pull request by lucernae**
In preparation for backend-frontend consistency checks

# The aim of the PR

- provides smaller scale testable docker-osm/postgres/postgrest backend creations to make sure it's relevant with frontend
- provides testable way to deploy changes of Forecast fetch script
- will be reused for rancher catalog recipes

# To Do

- [X] Refactor into configurable docker-compose recipe with local overrides
- [x] host smaller clip of testable pbf file somewhere
- [ ] hook up forecast fetch deploy into docker-osm db containers
- [ ] hook up into travis for integration checks between backend components
- [ ] if possible at all, hook up into github actions to continuously update staging site to deploy forecast script changes/schema changes (not sure if schema should be updated automatically)

### CODE REVIEW

**Comment by NyakudyaA** [comment]
Looks good @lucernae

**Comment by lucernae** [comment]
We host our PBF in cloud.kartoza.com :)

**Comment by timlinux** [comment]
> We host our PBF in cloud.kartoza.com :)

Can we not just keep it in the repo if it is a small one?

**Comment by lucernae** [comment]
> Can we not just keep it in the repo if it is a small one?
I would have done so if it's small, but this pbf is around 100+MB.
If the extent is smaller it maybe not so useful to test the building summary counts.

**Comment by lucernae** [comment]
I had to merge this and continue in another PR to avoid conflicts with @ann26 frontend development.

**Pull request merged**
